stages:
  - build
  - error_clean
  - test
  - documentation
  - deploy

cache:
  key: "$CI_BUILD_REF"
  paths:
    - build_gnu/
    - doc/doxygen/doxygen
    - doc/Meshformat/Meshformat.pdf


build_gnu:
  stage: build
  tags:
    - flexitag
  script:
    - mkdir -p build_gnu ; cd build_gnu
    - if [ -n "${DO_NIGHTLY}" ]; then cmake .. ; fi
    - if [ -z "${DO_NIGHTLY}" ]; then cmake .. -DLIBS_BUILD_HDF5=OFF ; fi
    - if [ -n "${DO_COVERAGE}" ]; then cmake .. -DCMAKE_BUILD_TYPE=Coverage ; fi
    - make all

clean:
  stage: error_clean
  tags:
    - flexitag
  script:
    - rm -rf build_gnu
    - rm -rf share
  when: on_failure

run_gnu:
  stage: test
  tags:
    - flexitag
  script:
    - cd tutorials ; ./executeall.sh ../build_gnu/bin/hopr
      
run_gnu_test:
  - stage: test
  - tags: 
    - flexitag
  - rules: 
    - if '${DO_COVERAGE}'
  - needs: ["run_gnu"]
  - script: 
    - gcovr --json --print-summary -o coverage_run_gnu.json -r ${CI_PROJECT_DIR}
    - gcovr --add-tracefile coverage_run_gnu.json --html-details coverage_run_gnu.html -r ${CI_PROJECT_DIR}
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_PIPELINE_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 4 days
    paths:
      - tutorials/coverage_run_gnu.json
      - tutorials/coverage_run_gnu.html
      

doxygen:
  stage: documentation
  tags:
    - flexitag
  script:
    - cd doc/doxygen ; ./builddoxy.sh

meshformat:
  stage: documentation
  tags:
    - flexitag
  script:
    - cd doc/Meshformat ; make

deploy_homepage:
  stage: deploy
  tags:
    - flexitag
  script:
    - if [ -n "${DO_DEPLOY}" ]; then if [ -d "doc/doxygen/doxygen" ]; then ssh flexi@euler rm -rf homepage_hopr/doxygen ; scp -r doc/doxygen/doxygen flexi@euler:~/homepage_hopr/. ; fi ; fi
    - if [ -n "${DO_DEPLOY}" ]; then if [ -f "doc/Meshformat/Meshformat.pdf" ]; then scp doc/Meshformat/Meshformat.pdf flexi@euler:~/homepage_hopr/. ; fi ; fi

deploy_github:
  stage: deploy
  tags:
    - flexitag
  script:
    - if [ -z "${DO_DEPLOY}" ]; then exit ; fi
    - git clone --single-branch git@gitlab.iag.uni-stuttgart.de:hopr/hopr.git hopr_github ; cd hopr_github ; git push --mirror git@github.com:flexi-framework/hopr.git ; cd ../
